### ISSUE TITLE
AI worker 2.0.1 launch failed on ubuntu 16.04：initialization error: driver error: failed to process request\\\\\\\\n\\\\\\\"\\\"\": unknown"

### ISSUE THREAD

**Issue by flyworker** [nebulaai/ai-worker#4]
"Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused \"process_linux.go:424: container init caused \\\"process_linux.go:407: running prestart hook 0 caused \\\\\\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=9.0 --pid=3758 /var/lib/docker/overlay2/b0bf26d71d15e322ddaeb3a6ee9e0cad6016db05794c2268b0f56072c535102a/merged]\\\\\\\\nnvidia-container-cli: initialization error: driver error: failed to process request\\\\\\\\n\\\\\\\"\\\"\": unknown"
The above is command and error response

**Comment by blueskyps2003** [comment]
solution:
This happens when a prerequisite image is missing. Use the following command to test/pull it:
sudo docker run --runtime=nvidia --rm nvidia/cuda:9.0-base nvidia-smi

e.g.,

 $ sudo docker run --runtime=nvidia --rm nvidia/cuda:9.0-base nvidia-smi
Wed Mar 20 16:06:35 2019       
Unable to find image 'nvidia/cuda:9.0-base' locally
9.0-base: Pulling from nvidia/cuda
7b722c1070cd: Already exists 
5fbf74db61f1: Already exists 
ed41cb72e5c9: Already exists 
7ea47a67709e: Already exists 
52efd3da8bcd: Pull complete 
eea82f174227: Pull complete 
0d7845ca9ae6: Pull complete 
Digest: sha256:6c77adf17b3e0188550afa02f88adc326195d845971a017c2317d0cf88f8b50b
Status: Downloaded newer image for nvidia/cuda:9.0-base
Wed Mar 20 16:05:46 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.104      Driver Version: 410.104      CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:02:00.0 Off |                  N/A |
|  0%   41C    P8     9W / 250W |      2MiB / 11178MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:17:00.0 Off |                  N/A |
|  0%   46C    P8     9W / 250W |      2MiB / 11178MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  Off  | 00000000:65:00.0  On |                  N/A |
|  9%   53C    P8    14W / 250W |    215MiB / 11175MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 108...  Off  | 00000000:66:00.0 Off |                  N/A |
|  0%   41C    P8     8W / 250W |      2MiB / 11178MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
Then,
launch the program again
./launch_nbai_worker
